#!/usr/bin/env python3

import yaml, subprocess

def docker(*cmd):
    print("+ docker " + " ".join(cmd))
    subprocess.check_call(("docker",) + cmd)

eth0 = subprocess.check_output(("ip", "addr", "list", "eth0")).decode("ascii").splitlines()
addr = [line for line in eth0 if "inet " in line][0].replace("/", " ").split()[1]
port = 8080
url  = "http://{}:{}/mutate".format(addr, port)

links = yaml.load(open("topology.yaml"))
nodes = set()
for link in links:
    nodes.update(link)
nodes = sorted(nodes)

docker("run", "-dit", "-p={}:{}:{}".format(addr, port, port), "--name", "kriek", "kriek")

for node in nodes:
    docker("run", "-dit", "--name", node, "--cap-add=NET_ADMIN", "lsoed")

for spine, leaf in links:
    net = "{}-{}".format(spine, leaf)
    docker("network", "create", net)
    docker("network", "connect", net, spine)
    docker("network", "connect", net, leaf)

for node in nodes:
    docker("exec", "-dit", node, "/app/configure", "--name", node, "--url", url)
