#!/usr/bin/env python3

# Read topology file to figure out what nodes need to be shut down at end of demo.
# Just exit quietly if no demo topology has been specified (yet).

import os, json

fn = "topology.json"

if os.path.exists(fn):
    nodes = { "kriek" }
    for left, right in json.load(open("topology.json")):
        nodes.add(left)
        nodes.add(right)
    for node in sorted(nodes):
        print(node)
